Downgrade juju
canonical/istio-operators pull request #272
Opened 2023-05-23 15:34 UTC by beliaev-maksim

we are on 2.9, thus, pylibjuju should be 2.9

2023-05-23 20:03 UTC, ca-scribner requested changes
I don't believe this PR is correct.  pylibjuju 3.0.x is supposed to be compatible with 2.9 and 3.x I believe, but also gets better patch updates than 2.9.x.  So I think it is the version we want in this case.  

I might be wrong about this though, I've been confused on which we need.  Was there something prompting this?

2023-05-23 20:08 UTC, beliaev-maksim commented
@ca-scribner I talked with Juan

3.0 is not maintained. All bug fixes are landed in 2.9, 3.1 and 3.2

2023-05-25 14:28 UTC, ca-scribner commented
ok sounds good to me then.  thanks!

2023-05-25 15:56 UTC, ca-scribner approved these changes

2023-05-25 17:03 UTC, merged